# =========================
# General experiment settings
# =========================
seed: 42
device: cuda
exp_name: # If none, this is the dataset name used: adult or compass
log_dir: './runs'

global:
  eval_freq: 5     # global fallback for evaluation frequency

# =========================
# Fairness metric selection
# =========================
metrics:
  use: ["D.DP", "D.EqOdds", "D.PRP", "D.Err", "L.ZeroOne"]
  use_demos_as_gruth: False

# =========================
# Subdominance configuration
# =========================
subdominance:
  # type: bayesian  # standard | stochastic
  mode: absolute
  rollout_aggregate: sum
  alpha: [1.,1.,1.,2.,3.] # Alpha defaults to 1. Alpha/beta scalars are broadcasted
  beta: 0. # If null defaults to 0
  adaptive_beta: false
  weight_mode: simple # simple, softmax, linear
  alpha_updates: analytical #analytical, static

# =========================
# Demonstrator configuration
# =========================
demonstrator:
  dataset: "adult" # adult or compas
  shared_x: True
  demotype: lrdecisions  # partition or lrdecisions
  # LR (Logistic Regression) Decisions Specific
  n_models: 100 # only used with lr decisions. How many classifier are trained. One per demo.
  subset_ratio: 0.1 # subset of training data that lr classifiers are used, but provide pred to entire train set.
  # Data Partition Specific
  demo_size: 100  # ingored with lr decisions, only used for partitions
  # General
  compute_global: true
  normalize: True # Constraint values
  normalize_mode: 'continuous'
  overwrite: False # True/ False. True will force regenerate the demos, even if they exist
  cache_dir: "./data"
  metrics: ["D.DP", "D.EqOdds", "D.PRP", "D.Err", "L.ZeroOne"] # Default list; overwritten by metrics above
  train_ratio: 0.8 # amount of data exclusively in training set
  protected_attrs:          # these are attributes are ommited from the the features
  sensitive_attrs: ['sex']  # these are the attributes  that fairness is measured on
  save_format: "zip" # zip or npy. with npy a separate json metadata file is saved at data folder
  demo_sample: null
  # Set to true to construct diagnostic set with 50% demos 50% RANDOM DECISIONS
  use_diagnostic_train: True
  use_diagnostic_eval: True

# =========================
# Learner configuration
# =========================
learner:
  schedule:
    - algo: subdominantLogistic #subdominantLogistic, subdominantmlp
      epochs: 2000
      eval_freq: 200
      train_print_freq: 100
      model_cfg:
        post_eval_transfer: False
        # policy_sources: ['random', 'logistic_model_adult_performance_0p1884_0p1289_0p0559_0p0903_0p1419.pkl']
        # policy_sources: ['logistic_model_adult_performance_0p1884_0p1289_0p0559_0p0903_0p1419.pkl']
        # policy_sources: ['logistic_model_adultpoor_performance_0p2638_0p1222_0p1846_0p0681_0p4236.pkl']
        # policy_sources: ['logistic_model_adult_performance_0p1884_0p1289_0p0559_0p0903_0p1419.pkl', 'logistic_model_adultpoor_performance_0p2638_0p1222_0p1846_0p0681_0p4236.pkl']
        policy_sources: ['random']
        policy_mixture: [1.]
        n_models: 1
        init_noise_std: 0.1
      train:
        lr: 0.003
        batch_size: 100
        n_rollouts: 10
        t_function: 'vec' # old, ref, vec, collect
        stochastic:
        
    # - algo: bayesianLogistic
    #   epochs: 100
    #   eval_freq: 4
    #   model_cfg:
    #     policy:
    #   train:
    #     lr: 0.001
    #     batch_size: 100
    #     bayesian:
    #       dist_mode: 'full_param_mvn'
    #       ema: 1.0
    #       max_mean_delta:
    #       var_ratio_clip: #[0.1, 10.0]

  # Each Phase will have the default values if non are given. When a kwarg is None above it stays None. 
  default:
    model_cfg:
    epochs: 10
    train:
      lr: 1e-3
      batch_size: 32
      optimizer: 'adam' # adam, sgd
      stochastic:
        solver: 'mosek'
        weighted_S_matrix: True
        row_constraints: False         # Bool
        col_constraints: 'rev_ranking' #'rev_ranking' # Options : None(uniform), rev_ranking, ranking
        ot_temperature: 1.0
        gamma_temperature: 1.0
        normalize_s_matrix: False
        renormalize_gamma: False
        loss_fn: 'weighted'
        loss_fn_kwargs: #for nested  dict be sure to include them into no_flatten_terms in line 88 base_model.py
          term_weights: [1., 1.]
      bayesian:
        n_rollouts: 256
        dist_mode: 'per_param_diag' # per_param_diag | per_layer_neuron_mvn | global_neuron_mvn
        ema : 0.2
        var_floor: 1e-8  
        cov_floor: 1e-5  
        shrinkage: 0.2
